apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- ../../bbp
images:
- name: ghcr.io/weaveworks/branch-based-planner
  newName: weaveworks/branch-based-planner
