{{- if .Values.branchPlanner.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.branchPlanner.configMap.name }}
data:
  secretName: {{ .Values.branchPlanner.configMap.name }}-token
  resources: |-
    - namespace: {{ .Release.Namespace }}
{{- end }}
