{{- if .Values.branchPlanner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "planner.labels" . | nindent 4 }}
  name: {{ include "planner.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "planner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "planner.selectorLabels" . | nindent 8 }}
    spec:
      {{- if not .Values.serviceAccount.create }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - args:
        - --log-encoding={{ .Values.logEncoding }}
        - --log-level={{ .Values.logLevel }}
        - --branch-polling-interval={{ .Values.branchPlanner.sourceInterval }}
        - --polling-configmap={{ .Values.branchPlanner.configMap }}
        - --polling-interval={{ .Values.branchPlanner.pollingInterval }}
        env:
          {{- include "pod-namespace" . | indent 8 }}
        image: "{{ .Values.branchPlanner.image.repository }}:{{ default .Chart.AppVersion .Values.branchPlanner.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 8080
          name: http-prom
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "tf-controller.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
{{- end }}
